<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'fe_news.features.inc';

/**
 * Implements hook_preprocess_node()
 */

function fe_news_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->type == 'news') {
    $author = '';
    if (!empty($node->field_attribution)) {
      $author = $node->field_attribution[$node->language][0]['value'];
    }
    else if (!empty($node->field_byline)) {
      $user = user_load($node->field_byline[$node->language][0]['uid']);
      $author = _fe_news_get_author($user);
    }
    else {
      $user = user_load($node->uid);
      $author = _fe_news_get_author($user);
    }

    $variables['author'] = $author;
  }
}

/**
 * Returns the author name linked to it's profile
 */
function _fe_news_get_author($user) {
  return l($user->field_screen_name[LANGUAGE_NONE][0]['value'],'user/'.$user->uid);
}


/**
 * Implements hook_theme()
 */

function fe_news_theme() {
  return array(
    'node__news' => array(
      'variables' => array('node' => array()),
      'template' => 'theme/node--news',
    ),
  );
}

/**
 * Implements hook_block_info()
 */

function fe_news_block_info() {
  $blocks = array();
  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function fe_news_block_view($delta = '') {
  $block = array();
  $vars = array();
  return $block;
}

/**
 * Implements hook_form_alter()
 */

function fe_news_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'comment_node_news_form') {
    hide($form['author']);
  }
}
