<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'fe_news.features.inc';

/**
 * Implements hook_preprocess_node()
 */

function fe_news_preprocess_node(&$variables) {
  global $base_url;

  $node = $variables['node'];
  if ($node->type == 'news') {
    $author = _fe_news_get_author($node->nid);
    $variables['author'] = $author->profile_link ?
      l($author->name, $author->profile_link) :
      $author->name;

    $href = $base_url . $variables['node_url'];
    drupal_add_html_head_link(
      array('rel' => 'canonical', 'href' => $href),
      TRUE
    );

    $tags_url = fe_news_redirect_tags($node->nid);
    $variables['url_tags'] = $tags_url;
  }
}


function fe_news_redirect_tags($nid = ''){
  if ($nid == '') {
    return '';
  }

  $tags = _fe_news_return_tags_array($nid);

  if (empty($tags)) {
    return '';
  }

  $tags_markup = '<section class="field field-name-field-tags field-type-taxonomy-term-reference field-label-inline clearfix view-mode-full"><h2 class="field-label">Tags:&nbsp;</h2><ul class="field-items">';

  $node = node_load($nid);

  if ($node->type == 'news') {
    $type = 'news';
  }   
  else if ($node->type == 'training_opportunity') {
    $type = 'opportunities';
  } else return '';

  foreach ($tags as $tid => $name) {
    $url = '/' . $type . '/' . $tid ;
    $tags_markup .=  '<li class="field-item-odd">' . '<a href="' . $url . '" >' . $name . '</a>';
  }

  $tags_markup  .= '</ul></section>';
  
  return $tags_markup;
}


//Devuelve un array con los tags del nodo: tid, name
function _fe_news_return_tags_array($nid = ''){
  global $language;

  $node = node_load($nid);

  $tags = array();
  if (isset($node->field_tags[$language->language])) {
    $tags = $node->field_tags[$language->language];
  }
  elseif (isset($node->field_tags[LANGUAGE_NONE])) {
    $tags = $node->field_tags[LANGUAGE_NONE];
  }

  $result = array();
  foreach ($tags as $tag) {
    $term = taxonomy_term_load($tag['tid']);
    $result[$tag['tid']] = $term->name;
  }

  return $result;
}

/**
 * Implements hook_theme()
 */

function fe_news_theme() {
  $themes = array(
    'node__news' => array(
      'variables' => array('node' => array()),
      'template' => 'theme/node--news',
    ),
    'last_posts_authors' => array(
      'variables' => array(
        'authors' => NULL,
      ),
      'template' => 'last-posts-authors',
      'path' => drupal_get_path('module', 'fe_news') . '/theme',
    ),
    'news_topic_block' => array(
      'template' => 'theme/topic-block',
      'variables' => array('name' => '', 'url' => ''),
    ),
  );

  return $themes;
}

/**
 * Implements hook_block_info()
 */

function fe_news_block_info() {
  $blocks = array();

  $blocks['last_posts_authors']  = array('info' => 'Gets authors for the last 10 posts.');
  $blocks['field_topic_block'] = array('info' => 'Bloque para los topics en el header');

  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function fe_news_block_view($delta = '') {
  $block = array();
  $vars = array();

  if ($delta == 'last_posts_authors') {
    $block = array(
      'subjet' => NULL,
      'content' => _fe_news_get_last_posts_authors(),
    );
  }
  else if ($delta == 'field_topic_block') {
    $block['subject'] = '';
    $block['content'] = _fe_news_get_topics();
  }
  return $block;
}

function _fe_news_get_last_posts_authors($tid = '') {
  global $language;
  $authors = array();
  $authors_uid = array();

  $view = views_get_view('last_posts');
  if ($view) {
    $view->set_display('block');
    if ($tid) {
      $view->set_arguments(array($tid));
    }
    $view->execute();
    foreach($view->result as $content){
      if (sizeof($authors) < 10) {
        $author = _fe_news_get_author($content->nid);
        if (!isset($author->uid)) {
          continue;
        }

        $user = user_load($author->uid);
        $keys = array_keys($user->field_show_profile);
        $show_profile = isset($user->field_show_profile[$keys[0]][0]['value']) ?
          $user->field_show_profile[$keys[0]][0]['value'] :
          FALSE;
        if ( $show_profile ) {

          if (isset($author->uid)) {
            if (!in_array($author->uid, $authors_uid)) {
              $authors_uid[] = $author->uid;
              $authors[] = $author;
            }
          } else {
            if (!in_array($author->name, $authors_uid)) {
              $authors_uid[] = $author->name;
              $authors[] = $author;
            }
          }
        }
      }
    }
  }


  return theme('last_posts_authors', array('authors' => $authors));
}

function _fe_news_get_author($nid) {
  $node = node_load($nid);
  $language = $node->language;

  $author = new stdClass();
  $author->profile_link = FALSE;
  if (!empty($node->field_attribution)) {
    $author->name = (isset($node->field_attribution[$language])) ?
      $node->field_attribution[$language][0]['safe_value'] :
      $node->field_attribution[LANGUAGE_NONE][0]['safe_value'];
  }
  else {
    if (!empty($node->field_byline)) {
      $user = (isset($node->field_byline[$language])) ?
        user_load($node->field_byline[$language][0]['uid']) :
        user_load($node->field_byline[LANGUAGE_NONE][0]['uid']);
    }
    else {
      $user = user_load($node->uid);
    }
    $author->uid = $user->uid;
    $author->name = _fe_news_get_safe_value($user, 'field_screen_name');
    $author->profile_link = drupal_get_path_alias('user/' . $user->uid);
    $author->avatar = isset($user->picture) ? 
      theme_image_style(array(
        'path' => $user->picture->uri, 
        'style_name' => 'avatar_small_img', 
        'width' => '110', 
        'height' => '110')
        ) :  null;
    $author->job = _fe_news_get_safe_value($user, 'field_job_title');
    $author->organization = _fe_news_get_safe_value($user, 'field_organization_name');
  }

  return $author;
}

/**
 * Implements hook_form_alter()
 */
function fe_news_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'comment_node_news_form') {
    hide($form['author']);
  }
}

/**
 * Helper to pull value regardless of language
 */
function _fe_news_get_safe_value($entity, $field_name) {
	global $language;

  if (!isset($entity->$field_name) || !is_array($entity->$field_name) || empty($entity->$field_name)) {
    return '';
  }

  // try to use value for current language
  $lang_code = $language->language;
	if (isset($entity->{$field_name}[$lang_code])) {
		$item = $entity->{$field_name}[$lang_code];
	}
	else if (isset($entity->{$field_name}['en'])) {
		// try english if available
    $item = $entity->{$field_name}['en'];
	}
	else {
    // use whatever we have.
    $keys = array_keys($entity->$field_name);
    $item = $entity->{$field_name}[$keys[0]];
	}
  $value = isset($item[0]['safe_value']) ?
    $item[0]['safe_value'] :
    '';

  return $value;
}

function _fe_news_get_topics($nid = '') {
  $nid = $nid ? $nid : arg(1);
  $node = node_load($nid);
  $exclusion_list = array(913, 914, 915, 916, 917, 918, 919);
  global $language;
  $tid = '';
  if (!empty($node->field_topic[$language->language])) {
    foreach ($node->field_topic[$language->language] as $topic) {
      if (!in_array($topic['tid'], $exclusion_list)) {
        $tid = $topic['tid'];
        break;
      }
    }
  }
  else if (!empty($node->field_category[LANGUAGE_NONE])) {
    $tid = ''; 
    foreach ($node->field_category[LANGUAGE_NONE] as $topic) {
      if (!in_array($topic['tid'], $exclusion_list)) {
        $tid = $topic['tid'];
        break;
      }   
    }
  }

  if ($tid) {
    $term = taxonomy_term_load($tid);
    $name = $term->name;
    $type = ''; 
    if ($node->type == 'news') {
      $type = 'news';
    }   
    else if ($node->type == 'training_opportunity') {
      $type = 'opportunities';
    }
    else if ($node->type == 'video') {
      $type = 'videos/topic';
    }
    $url = '/' . $language->language . '/' . $type . '/' . $tid;
    return theme('news_topic_block', array('name' => $name, 'url' => $url));
  } 
  return '';
}