<?php
/**
 * @file
 * Code for the Opportunity feature.
 */

include_once 'fe_opportunity.features.inc';

/**
 * Implements hook_theme()
 */
function fe_opportunity_theme() {
  return array(
    'node__training_opportunity' => array(
      'variables' => array('node' => array()),
      'template' => 'theme/node--training_opportunity',
    ),  
  );  
}

/**
 * Implements hook_preprocess_node()
 */
function fe_opportunity_preprocess_node(&$vars) {
  if ($vars['node']->type == 'training_opportunity') {
    $node = $vars['node'];
    if ($node->field_deadline && isset($node->field_deadline)) {
      global $language;
      $date = $node->field_deadline[$language->language][0]['value'];
      $vars['deadline_month'] = date('M j', $date);
      $vars['deadline_year'] = date('Y', $date);
    }else{
      $vars['deadline_month'] = t('ROLLING');
      $vars['deadline_year'] = '';
    }
    $vars['path'] = url('node/' . $node->nid);
    $topics = module_invoke('fe_news', 'block_view', 'field_topic_block');
    $vars['topics'] = $topics['content'];
    
    $tags_url = fe_news_redirect_tags($node->nid);
    $vars['url_tags'] = $tags_url;
  }
}

/**
 * Implements hook_form_alter
 */
function fe_opportunity_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-opportunities-views-opportunities-landing') {
    $form['field_category_tid']['#options']['All'] = t('Any');
    $form['field_region_tid']['#options']['All'] = t('Any');
    $form['keys']['#attributes']['placeholder'] = t('Search term...');
    $title = array('filter-search_title' => array("operator" => 'search_title_op', "value" => "search_title", "label" => '', "description" => ''));
    $form['#info'] = $title + $form['#info'];
    $form['search_title']['#markup'] = '<h3>' . t('SEARCH OPPORTUNITIES') . '</h3>';
  }

  if ($form_id == 'training_opportunity_node_form') {
    $lang = $form['language']['#value'];
    $form['field_deadline'][$lang][0]['timezone']['#default_value']= 'America/New_York';
    $form['field_deadline'][$lang][0]['timezone']['#disabled'] = TRUE;

  }
}

//Returns offset of $timezone to the one from the site. 
function _fe_opportunity_offset_tz($timezone) {
  $timeOffset = 0;

  if (isset($timezone)){
    $timezone_opp = new DateTimeZone($timezone);
    $timezone_default = new DateTimeZone(variable_get('date_default_timezone'));

    $date_default = new DateTime("now", $timezone_default);
    $date_opp = new DateTime("now", $timezone_opp);

    $timeOffset = $timezone_default->getOffset($date_opp) - $timezone_opp->getOffset($date_opp);
  }
  return $timeOffset;
}
