<?php
/**
 * @file
 * fe_opportunity.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function fe_opportunity_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_cost'.
  $field_bases['field_cost'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_cost',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
      'entity_translation_sync' => FALSE,
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_deadline'.
  $field_bases['field_deadline'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_deadline',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'entity_translation_sync' => FALSE,
      'granularity' => array(
        'day' => 'day',
        'hour' => 'hour',
        'minute' => 0,
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'timezone_db' => array(
        '#ajax_processed' => FALSE,
        '#array_parents' => array(
          0 => 'field',
          1 => 'settings',
          2 => 'timezone_db',
        ),
        '#attributes' => array(),
        '#defaults_loaded' => TRUE,
        '#id' => 'edit-field-settings-timezone-db',
        '#input' => TRUE,
        '#name' => 'field[settings][timezone_db]',
        '#parents' => array(
          0 => 'field',
          1 => 'settings',
          2 => 'timezone_db',
        ),
        '#process' => array(
          0 => 'ajax_process_form',
        ),
        '#processed' => TRUE,
        '#required' => FALSE,
        '#sorted' => TRUE,
        '#theme' => 'hidden',
        '#title_display' => 'before',
        '#tree' => TRUE,
        '#type' => 'hidden',
        '#validated' => TRUE,
        '#value' => 'America/New_York',
        '#weight' => 0.004,
      ),
      'todate' => '',
      'tz_handling' => 'date',
    ),
    'translatable' => 1,
    'type' => 'datestamp',
  );

  // Exported field_base: 'field_organization'.
  $field_bases['field_organization'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_organization',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'link',
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'rel' => '',
        'target' => 'default',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'entity_translation_sync' => FALSE,
      'title' => 'optional',
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
    ),
    'translatable' => 1,
    'type' => 'link_field',
  );

  // Exported field_base: 'field_region'.
  $field_bases['field_region'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_region',
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'region',
          'parent' => 0,
        ),
      ),
      'entity_translation_sync' => FALSE,
      'options_list_callback' => 'i18n_taxonomy_allowed_values',
    ),
    'translatable' => 1,
    'type' => 'taxonomy_term_reference',
  );

  return $field_bases;
}
