<?php
/**
 * @file
 * Code for the Newsletter feature.
 */

include_once 'fe_newsletter.features.inc';


define('FE_NEWSLETTER_MAX_ARTICLES',    100);

/**
 * Implements hook_menu()
 */
function fe_newsletter_menu() {
  $items['email-bulletin/%'] = array(
    'page callback' => 'ijnet_newsletter_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  $items['email-bulletin-archive'] = array(
    'page callback' => 'ijnet_newsletter_archive_callback',
    'access callback' => TRUE,
  );
  $items['email-bulletin-archive/%'] = array(
    'page callback' => 'ijnet_newsletter_archive_by_nid_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  $items['node/%/bulletin'] = array(
    'title' => 'Newsletter markup',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fe_newsletter_content_form'),
    'access callback' => 'ijnet_newsletter_access_callback',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_admin_paths()
 *
 * Declare a path to use the admin theme.
 */
function fe_newsletter_admin_paths() {
  $paths = array(
    'node/*/bulletin' => TRUE,
  );
  return $paths;
}

function ijnet_newsletter_callback($nid) {
  $node = node_load($nid);

  if ($node->type != 'bulletin_email') {
    drupal_goto('<front>');
  }

  // TODO: delivery callback
  $parameters = _ijnet_newsletter_content_theme_parameters($nid);
  $theme = theme('ijnet_newsletter', $parameters);

  print($theme);
}

function ijnet_newsletter_archive_callback() {
  $nid = _ijnet_newsletter_get_last_newsletter_nid();
  $parameters = _ijnet_newsletter_content_theme_parameters($nid);
  $theme = theme('ijnet_newsletter_content', $parameters);

  return $theme;
}

function ijnet_newsletter_archive_by_nid_callback($nid = null) {
  if (node_load($nid)) {
    $parameters = _ijnet_newsletter_content_theme_parameters($nid);
    $theme = theme('ijnet_newsletter_content', $parameters);

    return $theme;
  }
  drupal_goto('email-bulletin-archive');
}

function _ijnet_newsletter_content_theme_parameters($nid) {
  $node = node_load($nid);
  $logo = _fe_social_get_ijnet_logo_by_lang($node->language);
  $social_media_items = _fe_social_get_social_media_items($node->language);

  $parameters = array(
    'node' => $node,
    'social_media_items' => $social_media_items,
    'logo' => $logo,
    'language' => $node->language,
  );

  $pitch_to_ijnet = ($node->language == 'en') ? TRUE : FALSE;
  $parameters['pitch_to_ijnet'] = $pitch_to_ijnet;

  if ($pitch_to_ijnet) {
    $path = drupal_lookup_path("source", 'blog/pitch-ijnet');
    $node = menu_get_object("node", 1, $path);
    $wrapper = entity_metadata_wrapper('node', $node);
    $image = $wrapper->field_image->value();

    $pitch_to_ijnet_image_url = image_style_url('news_wide', $image['uri']);

    $parameters['pitch_to_ijnet_image_url'] = $pitch_to_ijnet_image_url;
  }

  return $parameters;
}

function _ijnet_newsletter_get_last_newsletter_nid() {
  global $language;
  $newsletter_lang = $language->language;
  $result = db_select('node', 'n')
    ->condition('n.type', 'bulletin_email')
    ->condition('n.language', $newsletter_lang)
    ->fields('n', array('nid'))
    ->orderBy('created', 'DESC')
    ->extend('PagerDefault')->limit(1)
    ->execute()
    ->fetch();
  $nid = $result->nid;

  return $nid;
}

function ijnet_newsletter_access_callback($nid) {
  $node = node_load($nid);
  if ($node->type != 'bulletin_email') {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_theme()
 */
function fe_newsletter_theme() {
  $theme_path = drupal_get_path('module', 'fe_newsletter') . '/theme';
  $themes = array(

    'ijnet_newsletter' => array(
      'variables' => array(
        'node' => null,
        'social_media_items' => null,
        'logo' => null,
      ),
      'template' => 'ijnet-newsletter',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_content' => array(
      'variables' => array(
        'node' => null,
        'social_media_items' => null,
        'logo' => null,
        'pitch_to_ijnet' => null,
        'pitch_to_ijnet_image_url' => null,
      ),
      'template' => 'ijnet-newsletter-content',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_featured_contents' => array(
      'variables' => array(
        'featured_contents' => null,
      ),
      'template' => 'ijnet-newsletter-featured-contents',
      'path' => $theme_path,
    ),
    'ijnet_newsletter_featured_content' => array(
      'variables' => array(
        'featured_content' => null,
      ),
      'template' => 'ijnet-newsletter-featured-content',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_pitch_to_ijnet' => array(
      'variables' => array(
        'pitch_to_ijnet_image_url' => null,
      ),
      'template' => 'ijnet-newsletter-pitch-to-ijnet',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_advertisements' => array(
      'variables' => array(
        'advertisements' => null,
      ),
      'template' => 'ijnet-newsletter-advertisements',
      'path' => $theme_path,
    ),
    'ijnet_newsletter_advertisement' => array(
      'variables' => array(
        'advertisement' => null,
      ),
      'template' => 'ijnet-newsletter-advertisement',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_opportunities' => array(
      'variables' => array(
        'opportunities' => null,
      ),
      'template' => 'ijnet-newsletter-opportunities',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_opportunity' => array(
      'variables' => array(
        'opportunity' => null,
      ),
      'template' => 'ijnet-newsletter-opportunity',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_multimedia_items' => array(
      'variables' => array(
        'multimedia_items' => null,
      ),
      'template' => 'ijnet-newsletter-multimedia-items',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_multimedia' => array(
      'variables' => array(
        'multimedia' => null,
      ),
      'template' => 'ijnet-newsletter-multimedia',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_comments' => array(
      'variables' => array(
        'comments' => null,
      ),
      'template' => 'ijnet-newsletter-comments',
      'path' => $theme_path,
    ),

    'ijnet_newsletter_comment' => array(
      'variables' => array(
        'comment' => null,
      ),
      'template' => 'ijnet-newsletter-comment',
      'path' => $theme_path,
    ),
  );

  return $themes;
}

/**
 * Implements template_preprocess_hook()
 */
function template_preprocess_ijnet_newsletter_content(&$vars) {
  $node = $vars['node'];

  $vars['newsletter_date'] = _fe_newsletter_format_date($node->created, $node->language);
  $vars['newsletter_images_path'] = drupal_get_path('module', 'fe_newsletter') . '/theme/images/';
  $vars['link_site'] = '<a href="http://ijnet.org/' . $node->language . '"  style="font-family: verdana, arial,sans-serif; font-weight: bold; text-decoration: none;">';
  $vars['link_contact'] ='<a href="http://ijnet.org/'. $node->language .'/about/#contact-site-form" style="font-family: verdana, arial,sans-serif; font-weight: bold; text-decoration: none;">';
  $vars['featured_contents'] = _fe_newsletter_get_featured_contents($node);
  $vars['advertisements'] = _fe_newsletter_get_advertisements($node);
  $vars['opportunities'] =_fe_newsletter_get_opportunities($node);
  $vars['multimedia_items'] = _fe_newsletter_get_multimedia_items($node);
  $vars['comments'] = _fe_newsletter_get_comments($node);
}

/**
 * Implements hook_preprocess_page(&$vars)
 */
function fe_newsletter_preprocess_page(&$vars) {
  if (arg(0) == 'email-bulletin-archive') {
    drupal_add_js(
      drupal_get_path('module', 'fe_newsletter') . '/js/fe_newsletter.js',
      'file'
    );
  }

  if (current_path() == 'videos') {
    $module_path = drupal_get_path('module', 'fe_newsletter');
    drupal_add_js(
      $module_path . '/js/fe_newsletter_subscribe_videos.js', 'file'
    );

  }
}

function _fe_newsletter_format_date($date, $language = 'en') {
  $format = ($language == 'en') ? 'm/d/Y' : 'd/m/Y';
  $formated_date = format_date(
    $date,
    $type = 'custom',
    $format,
    $timezone = null, 
    $langcode = $language
  );

  return $formated_date;
}

function _fe_newsletter_get_featured_contents($node) {
  $language = $node->language;

  $featured_contents = array();
  if (!empty($node->field_other_content)) {
    $featured_contents_nids = isset($node->field_other_content[$language]) ?
      $node->field_other_content[$language] :
      $node->field_other_content[LANGUAGE_NONE];
    foreach ($featured_contents_nids as $nid) {
      $featured_contents[] = _fe_newsletter_get_featured_content($nid['nid']);
    }
  }

  return $featured_contents;
}

function _fe_newsletter_get_featured_content($nid) {

  $node = node_load($nid);

  $language = $node->language;
  $installed_languages = language_list();

  $featured_content = new stdClass();
  if (empty($node->field_image)) {
    $featured_content->image = NULL;
  } else {
    $featured_content->image = isset($node->field_image[$language]) ?
      $node->field_image[$language][0]['uri'] :
      $node->field_image[LANGUAGE_NONE][0]['uri'];
  }
  if (empty($node->title_field)) {
    $featured_content->title = NULL;
  } else {
    $featured_content->title = isset($node->title_field[$language]) ?
      $node->title_field[$language][0]['safe_value'] :
      $node->title_field[LANGUAGE_NONE][0]['safe_value'];
  }
  if (empty($node->summary)) {
    $featured_content->summary = NULL;
  } else {
    $featured_content->title = isset($node->body[$language]) ?
      $node->body[$language][0]['safe_summary'] :
      $node->body[LANGUAGE_NONE][0]['safe_summary'];
  }

  $featured_content->author = _fe_newsletter_get_author($nid);

  $featured_content->link = url('node/' . $nid, array('absolute' => TRUE, 'language' => $installed_languages[$language]));

  return $featured_content;
}

function _fe_newsletter_get_author($nid) {
  $node = node_load($nid);
  $author = _fe_news_get_author($nid);
  $result = $author->profile_link ?
    "<a href=" . url($author->profile_link, array('absolute' => TRUE)) . ">" . $author->name . "</a>" :
    $author->name;

  return $result;
}

function _fe_newsletter_get_advertisements($node) {
  $language = $node->language;

  $advertisements = array();
  if (empty($node->field_advertisements)) {
  } else {
    $advertisements_nids = isset($node->field_advertisements[$language]) ?
      $node->field_advertisements[$language] :
      $node->field_advertisements[LANGUAGE_NONE];
    foreach ($advertisements_nids as $nid) {
      $advertisements[] = _fe_newsletter_get_advertisement($nid['nid']);
    }
  }
  
  return $advertisements;
}

function _fe_newsletter_get_advertisement($nid) {
  $node = node_load($nid);
  $language = $node->language;
  $installed_languages = language_list();

  $advertisement = new stdClass();
  if (empty($node->field_image)) {
    $advertisement->image = NULL;
  } else {
    $advertisement->image = isset($node->field_image[$language]) ?
      $node->field_image[$language][0]['uri'] :
      $node->field_image[LANGUAGE_NONE][0]['uri'];
  }
  $advertisement->title = $node->title;
  if (empty($node->body)) {
    $advertisement->summary = NULL;
  } else {
    $advertisement->summary = strip_tags (isset($node->body[$language]) ?
      $node->body[$language][0]['safe_summary'] :
      $node->body[LANGUAGE_NONE][0]['safe_summary']);
  }
  $advertisement->link = url('node/' . $nid, array('absolute' => TRUE, 'language' => $installed_languages[$language]));

  return $advertisement;
}

function _fe_newsletter_get_opportunities($node) {
  $language = $node->language;

  $opportunities = array();
  if (!empty($node->field_opportunities)) {
    $opportunities_nids = isset($node->field_opportunities[$language]) ?
      $node->field_opportunities[$language] :
      $node->field_opportunities[LANGUAGE_NONE];
    foreach ($opportunities_nids as $nid) {
      $opportunity = _fe_newsletter_get_opportunity($nid['nid']);
      if ($opportunity) {
        $opportunities[] = $opportunity;
      }
    }
  }
  $classified_opportunities = _fe_newsletter_classify_opportunities($opportunities);

  return $classified_opportunities;
}

function _fe_newsletter_get_opportunity($nid) {
  $node = node_load($nid);
  if (!isset($node->nid)) {
    return FALSE;
  }

  $language = $node->language;
  $installed_languages = language_list();

  $opportunity = new stdClass();
  $opportunity->title = $node->title;
  if (empty($node->body)) {
    $opportunity->summary = NULL;
  } else {
    $opportunity->summary = isset($node->body[$language]) ?
      $node->body[$language][0]['safe_summary'] :
      $node->body[LANGUAGE_NONE][0]['safe_summary'];
  }
  if (empty($node->field_deadline)) {
    $deadline = NULL;
  } else {
    $deadline = isset($node->field_deadline[$language]) ?
      $node->field_deadline[$language][0]['value'] :
      $node->field_deadline[LANGUAGE_NONE][0]['value'];
  }
  if ($deadline) {
    $opportunity->deadline = _fe_newsletter_format_date($deadline, $language);
  }
  if (empty($node->field_region)) {
    $opportunity->tid = NULL;
  } else {
    $opportunity->tid = isset($node->field_region[$language]) ?
      $node->field_region[$language][0]['tid'] :
      $node->field_region[LANGUAGE_NONE][0]['tid'];
  }
  $opportunity->link = url('node/' . $nid, array('absolute' => TRUE, 'language' => $installed_languages[$language]));
  if ($opportunity->summary != NULL) {
      $opportunity->summary = strip_tags($opportunity->summary);
  }
  return $opportunity;
}

function _fe_newsletter_classify_opportunities($opportunities) {
  $classified_opportunities = array();
  $region_vocabulary = taxonomy_vocabulary_machine_name_load('region');
  $taxonomy_tree = taxonomy_get_tree($region_vocabulary->vid, $parent = 0, $max_depth = 1);
  $worldwide = $taxonomy_tree[0];
  $regions_tid = taxonomy_get_tree($region_vocabulary->vid, $worldwide->tid, $max_depth = 1);

  $classified_opportunities[$worldwide->tid] = array();
  $regions = array();
  $regions[$worldwide->tid] = t($worldwide->name);
  foreach ($regions_tid as $region) {
    $classified_opportunities[$region->tid] = array();
    $regions[$region->tid] = t($region->name);
  }

  foreach ($opportunities as $opportunity) {
    $opportunity->tid = isset($opportunity->tid) ?
      $opportunity->tid :
      $worldwide->tid;
    $opportunities_parents = taxonomy_get_parents_all($opportunity->tid);
    $index = 0;
    if (sizeof($opportunities_parents) > 1) {
      $index = sizeof($opportunities_parents) - 2;
    }
    $classified_opportunities[$opportunities_parents[$index]->tid][] = $opportunity;
  }
  $classified_opportunities[0] = $regions;

  return $classified_opportunities;
}

function _fe_newsletter_get_multimedia_items($node) {
  $language = $node->language;

  $multimedia_items = array();
  if (!empty($node->field_multimedia)) {
    if (isset($node->field_multimedia[$language])) {
      $multimedia_nids = $node->field_multimedia[$language];
    }
    else {
      $multimedia_nids = $node->field_multimedia[LANGUAGE_NONE];
    }

    foreach ($multimedia_nids as $nid) {
      $multimedia = _fe_newsletter_get_multimedia($nid['nid']);
      if ($multimedia) {
        $multimedia_items[] = $multimedia;
      }
    }
  }

  return $multimedia_items;
}

function _fe_newsletter_get_multimedia($nid) {
  $node = node_load($nid);
  if (!isset($node->nid)) {
    return FALSE;
  }
  $wrapper = entity_metadata_wrapper('node', $node);

  $multimedia = new stdClass();
  $multimedia->title = $node->title;

  if (!empty($node->body)) {
    $body_info = $wrapper->body->value();
    $multimedia->body = $body_info['value'];
  }
  else {
    $multimedia->body = NULL;
  }

  if (!empty($node->field_image)) {
    $image_info = $wrapper->field_image->value();
    $multimedia->image = $image_info['uri'];
  }
  else {
    $multimedia->image = NULL;
  }

  if (!empty($node->field_multimedia_link)) {
    $link = $wrapper->field_multimedia_link->value();
    $multimedia->link_title = $link['title'];
    $multimedia->link_url = $link['url'];
  }

  return $multimedia;
}

function _fe_newsletter_get_comments($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $comments = array();
  if (!empty($node->field_comments)) {
    $referenced_comments = $wrapper->field_comments->value();
    foreach ($referenced_comments as $referenced_comment) {
      $comment = _fe_newsletter_get_comment($referenced_comment);
      if ($comment) {
        $comments[] = $comment;
      }
    }
  }

  return $comments;
}

function _fe_newsletter_get_comment($referenced_comment) {
  $language = $referenced_comment->language;
  $comment = new stdClass();
  $comment->subject = $referenced_comment->subject;
  $comment->date = format_date($referenced_comment->created);
  $comment->author = $referenced_comment->name;

  $related_content = node_load($referenced_comment->nid);
  $comment->post_title = $related_content->title;
  $comment->post_url = "/" . drupal_get_path_alias("node/" . $related_content->nid);

  if (!empty($referenced_comment->comment_body)) {
    if (isset($referenced_comment->comment_body[$language])) {
      $body_info = $referenced_comment->comment_body[$language];
    }
    else {
      $body_info = $referenced_comment->comment_body[LANGUAGE_NONE];
    }
    $comment->body = $body_info[0]['value'];
  }
  else {
    $comment->body = NULL;
  }

  return $comment;
}

function fe_newsletter_content_form($form, &$form_state) {
  $nid = arg(1);
  $node = node_load($nid);
  $language = $node->language;
  $parameters = _ijnet_newsletter_content_theme_parameters($nid);
  $newsletter_content = theme('ijnet_newsletter', $parameters);
  $newsletter_link =
    '<div id="newsletter-link"><a href="' . 
    url('email-bulletin/' .  $nid) . 
    '" target="_blank">' . t("View the Newsletter") . '</a></div>';

  $form['newsletter_content'] = array(
    '#type' => 'textarea',
    '#title' => t(''),
    '#description' => t(''),
    '#default_value' => $newsletter_content,
    '#rows' => 20,
    '#field_prefix' => $newsletter_link,
  );

  return $form;
}

/**
 * Subscribe to newsletter form
 *
 * Form submits via AJAX. See: https://www.drupal.org/node/2081275
 */
function fe_newsletter_subscribe_form($form, &$form_state) {
  // Make these fields required.
  $form['#attributes']['class'][] = 'subscribe-form';

  $form['intro_text'] = array(
    '#markup' => '<p>'.t('Subscribe to our weekly bulletin for tips, trends and training opportunities.').'</p>'
  );
  $form['email'] = array(
    '#type' => 'textfield',
    //'#title' => t('Email address'),
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('EMAIL ADDRESS')),
  );
  $form['archive'] = array(
    '#markup' => '<a href="' . url('email-bulletin-archive') . '" " class="archive-link">' . t('Bulletin Archive') . '</a>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#attributes' => array('class'=>array('button-tiny')),
    '#ajax' => array(
      'callback' => 'fe_newsletter_subscribe_form_ajax_submit',
      'wrapper' => 'form-register-message'
    ),
  );
  $form['#suffix'] = '<div id="form-register-message"></div>';

  return $form;
}

function fe_newsletter_subscribe_form_ajax_submit($form, $form_state) {
  $contact = new stdClass();
  $contact->name = $form_state['values']['name'];
  $contact->email = $form_state['values']['email'];

  $success_code = _fe_newsletter_cc_subscribe_contact($contact);
  $cc_message = _fe_newsletter_cc_get_message($success_code);

  $message = $cc_message;
  $commands = array();
  if ($success_code == 200 or $success_code == 210) {
    $commands[] = ajax_command_remove('.subscribe-form');
    // Send event to GTM if module is enabled
    if (module_exists('ijnet_gtm')) {
      // notify GTM
      $args = array('event' => 'BulletinSubscribe');
      $commands[] = ajax_command_invoke('body', 'ijnet_gtm_push_event', array($args));
    }
  }
  $commands[] = ajax_command_replace('#form-register-message', $message);

  // Process form submission.
  $output = array('#type' => 'ajax', '#commands' => $commands);
  return $output;
}

function _fe_newsletter_cc_subscribe_contact($contact) {
  if(_fe_newsletter_cc_contact_exist($contact->email)) {
    $success_code = _fe_newsletter_cc_update_list($contact) ? 210 : 211;
  } else {
    $success_code = _fe_newsletter_cc_subscribe_list($contact) ? 200 : 201;
  }

  return $success_code;
}

function _fe_newsletter_cc_get_connection() {
  $action_type = 'contact';
  $cc_object = constant_contact_create_object();
  $cc_object->set_action_type($action_type);

  return $cc_object;
}

function _fe_newsletter_cc_contact_exist($email) {
  $cc = _fe_newsletter_cc_get_connection();
  $contact = $cc->query_contacts($email);
  $exist = $contact && ($contact['Status'] == 'Active');

  return $exist;
}

function _fe_newsletter_cc_get_contact($email) {
  $cc = _fe_newsletter_cc_get_connection();
  $contact = $cc->query_contacts($email);
  $contact = $cc->get_contact($contact['id']);

  return $contact;
}

function _fe_newsletter_cc_subscribe_list($contact) {
  $cc = _fe_newsletter_cc_get_connection();
  $list_id = _fe_newsletter_get_cc_list_id();
  $fields = array(
    'EmailType' => 'HTML',
    'FirstName' => $contact->name,
  );
  $cc_contact = $cc->query_contacts($contact->email);
  $status = array('Removed', 'Do Not Mail');
  $cc_contact && (in_array($cc_contact['Status'], $status)) ?
    $success = $cc->update_contact($cc_contact['id'], $contact->email, array($list_id), $fields) :
    $success = $cc->create_contact($contact->email, array($list_id), $fields) ;

  return $success;
}

function _fe_newsletter_cc_update_list($contact) {
  $cc = _fe_newsletter_cc_get_connection();
  $cc_contact = _fe_newsletter_cc_get_contact($contact->email);
  $list_id = _fe_newsletter_get_cc_list_id();
  if (in_array($list_id, $cc_contact['lists'])) {
    $success = false;
  } else {
    $lists = array_merge(array($list_id), $cc_contact['lists']);
    $fields = array(
      'EmailType' => 'HTML',
      'FirstName' => $contact->name,
    );
    $success = $cc->update_contact($cc_contact['id'], $contact->email, $lists, $fields);
  }

  return $success;
}

function _fe_newsletter_get_cc_list_id() {
  global $language;

  $cc_lists = array(
    'und' => 1316537398,
    'en' =>  1316537398,
    'es' =>  1265529464,
    'ru' =>  1833122425,
    'pt-br' => 1485709704,
    'zh-hans' => 1876266686,
    'ar' =>  1385780866,
    'fa' =>  1321747649,
  );
  $list_id = $cc_lists[$language->language];

  return $list_id;
}

function _fe_newsletter_cc_get_message($success_code) {
  $cc_messages = array(
    200 => array(
      'type' => 'success',
      'message' => 'Success, you are now subscribed to our mailing list. ',
    ),
    201 => array(
      'type' => 'sorry',
      'message' => 'Sorry, there was a problem, please ensure your details are valid and try again. ',
    ),
    210 => array(
      'type' => 'success',
      'message' => 'Success, you are now subscribed to our mailing list. ',
    ),
    211 => array(
      'type' => 'sorry',
      'message' => 'Sorry, you are subscribed to our mailing list. ',
    ),
  );
  $message = "<div class=\"{$cc_messages[$success_code]['type']}\">"
    .t($cc_messages[$success_code]['message']);
  global $language;
  $success_message = $cc_messages[$success_code]['type'] == 'success';
  if ($success_message && ($language->language == 'en')) {
    $sf_message = "You've subscribed to IJNet's bulletin. "
      . "If you also want to receive ICFJ news, click "
      . l(t('here'), 'contact-ijnet');
      $message .= $sf_message;
    }
  $message .= "</div>";

  return $message;
}

/**
 * Implements hook_node_presave().
 *
 * Add node news, videos and avertisements to newsletter on save.
 */
function fe_newsletter_node_presave($node) {
  // Only handle bulletin emails
  if ($node->type != 'bulletin_email') {
    return;
  }

  $newsletter_lang = $node->language;

  $from_date = isset($node->field_from_date[LANGUAGE_NONE][0]['value']) 
    ? strtotime($node->field_from_date[LANGUAGE_NONE][0]['value']) : NULL;
  $to_date  = isset($node->field_from_date[LANGUAGE_NONE][0]['value2']) 
    ? strtotime($node->field_from_date[LANGUAGE_NONE][0]['value2']) : NULL;
  $to_date += 24*60*60; // Add a day.

  $edit_date = FALSE;
  if (isset($node->nid)) { //edit
    $old_node = node_load($node->nid);
    $old_from_date = isset($old_node->field_from_date[LANGUAGE_NONE][0]['value'])
    ? strtotime($old_node->field_from_date[LANGUAGE_NONE][0]['value']) : NULL;
    $old_to_date = isset($old_node->field_from_date[LANGUAGE_NONE][0]['value2'])
    ? strtotime($old_node->field_from_date[LANGUAGE_NONE][0]['value2']) : NULL;
    $old_to_date += 24*60*60; // Add a day.

    if ($from_date != $old_from_date || $to_date != $old_to_date) {
      //reset content
      $node->field_other_content[LANGUAGE_NONE] = array();
      $node->field_opportunities[LANGUAGE_NONE] = array();
      $node->field_advertisements[LANGUAGE_NONE] = array();
      $edit_date = TRUE;
    }
  }

  // query news articles and videos
  if ($node->is_new || ! isset($node->nid) || $edit_date) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', array('news', 'video', 'training_opportunity'), 'IN')
      ->propertyCondition('status', 1)
      ->propertyCondition('language', $newsletter_lang)
      ->propertyCondition('created', $to_date, '<=')
      ->propertyCondition('created', $from_date, '>=')
      ->propertyOrderBy('created', 'DESC')
      ->range(0, FE_NEWSLETTER_MAX_ARTICLES);
    $result = $query->execute();

    if (isset($result['node'])) {
      // get nids which were specified
      $last_item = count($node->field_other_content[LANGUAGE_NONE]);
      $nids = array();
      if ($last_item > 0) {
        foreach($node->field_other_content[LANGUAGE_NONE] as $existing_content) {
          $nids[$existing_content['nid']] = $existing_content['nid'];
        }
      }

      // Add other nids
      $item_nids = array();
      $op_nids = array();
      foreach ($result['node'] as $key => $content) {
        if ($content->type != 'training_opportunity') {
          $item_nids[] = $key;
        }
        else {
          $op_nids[] = $key;
        }
      }
      //$item_nids = array_keys($result['node']);
      foreach($item_nids as $nid) {
        $nids[$nid] = $nid;
      }

      // Overwrite nids
      $field_content = array();
      foreach($nids as $nid) {
        $field_content[] = array('nid' => $nid);
      }
      $node->field_other_content[LANGUAGE_NONE] = $field_content;

      if (!empty($op_nids)) {
        $nids = array();
        $has_op = count($node->field_opportunities[LANGUAGE_NONE]);
        if ($has_op > 0) {
          foreach ($node->field_opportunities[LANGUAGE_NONE] as $existing_op) {
            $nids[$existing_op['nid']] = $existing_op['nid'];
          }
        }
        foreach ($op_nids as $nid) {
          $nids[$nid] = $nid;
        }
        $field_content = array();
        foreach ($nids as $nid) {
          $field_content[] = array('nid' => $nid);
        }
        $node->field_opportunities[LANGUAGE_NONE] = $field_content;
      }
    }

    // add advertisements
    $number_of_ads =
      isset($node->field_number_of_advertisements[LANGUAGE_NONE][0]['value']) ?
      $node->field_number_of_advertisements[LANGUAGE_NONE][0]['value'] : 4;
    $advs_nids =
      _fe_newsletter_query_advertisements($newsletter_lang, $number_of_ads);
    foreach($advs_nids as $index => $nid) {
      $node->field_advertisements[$newsletter_lang][$index]['nid'] = $nid;
    }
  }
}

function _fe_newsletter_query_advertisements($language = 'en', $limit = 4) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', 'advertisement')
    ->condition('n.status', 1)
    ->condition('n.language', $language)
    ->orderBy('n.sticky', "DESC")
    ->orderBy('n.created', "DESC")
    ->range(0,$limit);
  $result = $query->execute()->fetchAllAssoc('nid');
  $advertisements = array_keys($result);

  return $advertisements;
}

/**
 * Implements hook_user_update(&$edit, $account, $category)
 */

function fe_newsletter_user_update(&$edit, $account, $category) {
  $new_select_subscribe = $edit['field_subscribe']['und'][0];
  $contact = array(
    'name' => $edit['name'],
    'email' => $edit['mail'],
  );
  if ($new_select_subscribe['value'] == 1) {
    $code_success = _fe_newsletter_cc_subscribe_contact((object)$contact);
  }
  elseif ($new_select_subscribe['value'] == 0) {
    $code_success = _fe_newsletter_unsubscribed($contact['email']);
  }
}

function _fe_newsletter_unsubscribed($email) {
  $cc = _fe_newsletter_cc_get_connection();
  $contact = $cc->query_contacts($email);
  $success = $cc->delete_contact($contact['id']);
}

