<?php
/**
 * @file
 * Code for the User feature.
 */

include_once 'fe_user.features.inc';

function fe_user_preprocess_user_profile(&$vars) {
	$twitter_link = NULL;
	$user_profile = $vars['user_profile'];
	if ($user_profile['field_screen_name']['#object']->field_twitter){
		
	    $twitter_link =  l( " @" . drupal_strtoupper($user_profile['field_screen_name']['#object']->field_twitter['und'][0]['value']), 
	     	"http://www.twitter.com/@".$user_profile['field_screen_name']['#object']->field_twitter['und'][0]['value'],
	     	array('attributes' => array('target'=>'_blank'))
	     	);
	}
	$vars['twitter_link'] = $twitter_link;
}
