<?php
/**
 * @file
 * Code for the Chat feature.
 */

include_once 'fe_chat.features.inc';

/*
 * implements hook_preprocess_node
 */

function fe_chat_preprocess_node(&$vars) {
  if ($vars['node']->type == 'chat') {
    if (isset($vars['field_date'])) {
      if (!$vars['teaser']) {
        $start_date = format_date($vars['field_date'][0]['value'], $type = 'chat_long_start');
        $end_date = format_date($vars['field_date'][0]['value2'], $type = 'chat_long_end');
      }
      else {
        $start_date = format_date($vars['field_date'][0]['value'], $type = 'chat_short_start');
        $end_date = format_date($vars['field_date'][0]['value2'], $type = 'chat_short_end');
      }
      $vars['date'] = $start_date . ' - ' . $end_date;
    }
  }
}

/*
 * implements hook_theme
 */

function fe_chat_theme() {
  return array(
    'node__chat' => array(
      'variables' => array('node' => array()),
      'template' => 'theme/node--chat',
    ),  
  );  
}

