<?php
/**
 * @file
 * Code for the Knight Foundation feature.
 */

include_once 'fe_knight_foundation.features.inc';

/**
 * Implements hook_block_info().
 */
function fe_knight_foundation_block_info() {
  return array(
    'knight_authors_tab' => array(
      'info' => 'Tab de knights foundation para autores.',
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function fe_knight_foundation_block_view($delta = '') {
  $block = array();
  if ($delta == 'knight_authors_tab') {
    $block['content']  = fe_knight_foundation_get_authors(); 
    $block['subject'] = '';
  }
  return $block;
}

/**
 * Implements hook_views_query_alter().
 */
function fe_knight_foundation_views_query_alter(&$view, &$query) {
  if ($view->name == 'twitter' && $view->current_display == 'knight_foundation_tweets') {
    foreach($query->where[1]['conditions'] as $index => $condition) {
      if ($query->where[1]['conditions'][$index]['field'] == 'twitter.screen_name') {
        $accounts = variable_get('fe_knight_foundation_tweets', 'IJNet');
        $query->where[1]['conditions'][$index]['value'] = explode(',', $accounts);
        $query->where[1]['conditions'][$index]['operator'] = 'IN';
      }   
    }  
  }
}

function fe_knight_foundation_get_authors() {
  $topic = array(
    'en' => '913',
    'es' => '914',
    'ru' => '915',
    'ar' => '916',
    'zh-hans' => '917',
    'fa' => '919',
    'pt-br' => '918',
  );
  global $language;
  return _fe_news_get_last_posts_authors($topic[$language->language]);
}

/**
 * Implements hook_menu().
 */
function fe_knight_foundation_menu() {
  $items = array();
  $items['admin/config/administration/knight-tweets'] = array(
    'title'           => t('Admin for Knight Foundation Twitter accounts'),
    'description'  => t('Knight Foundation\'s twitter accounts admin page'),
    'page callback'   => 'drupal_get_form',
    'page arguments' => array('fe_knight_foundation_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );  
  return $items;
}


function fe_knight_foundation_form() {
  $form['twitters'] = array(
    '#title' => t('Twitter list'),
    '#type' => 'textarea',
    '#description' => t('Write down all the twitter acounts that you want to get listed on knight foundation\'s twitter block, separated by a comma'),
    '#default_value' => variable_get('fe_knight_foundation_tweets', 'IJNet'),
  );
  $form['submit'] = array(                                                                                                                                                      
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function fe_knight_foundation_form_submit($form, &$form_state) {
  $accounts = $form_state['input']['twitters'];
  variable_set('fe_knight_foundation_tweets', $accounts);
  drupal_set_message(t('Your configuration has been succesfully saved.'), 'status');
  return;
}
