<?php
/**
 * @file
 * Code for the Knight Foundation feature.
 */

include_once 'fe_knight_foundation.features.inc';

/**
 * Implements hook_preprocess_page(&$vars)
 */
function fe_knight_foundation_preprocess_page(&$vars) {
  $last_posts_authors_limit = variable_get('fe_knight_foundation_last_posts_authors_limit', 3);
  drupal_add_js(
    array(
      'fe_knight_foundation' => array('limit' => $last_posts_authors_limit)
    ),
    'setting'
  );
  $module_path = drupal_get_path('module', 'fe_knight_foundation');
  drupal_add_js($module_path .'/js/fe_knight_foundation.js');
}

/**
 * Implements hook_block_info().
 */
function fe_knight_foundation_block_info() {
  return array(
    'knight_authors_tab' => array(
      'info' => 'Tab de knights foundation para autores.',
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function fe_knight_foundation_block_view($delta = '') {
  $block = array();
  if ($delta == 'knight_authors_tab') {
    $block['content']  = fe_knight_foundation_last_posts_authors_callback();
    $block['subject'] = '';
  }
  return $block;
}

function fe_knight_foundation_last_posts_authors_callback() {
  $last_posts_authors = _fe_knight_foundation_get_last_posts_authors();

  return theme(
    'last_posts_authors',
    array(
      'authors' => $last_posts_authors,
      'show_more' => TRUE
    )
  );
}

/**
 * Implements hook_views_query_alter().
 */
function fe_knight_foundation_views_query_alter(&$view, &$query) {
  if ($view->name == 'twitter' && $view->current_display == 'knight_foundation_tweets') {
    foreach($query->where[1]['conditions'] as $index => $condition) {
      if ($query->where[1]['conditions'][$index]['field'] == 'twitter.screen_name') {
        $accounts = variable_get('fe_knight_foundation_tweets', 'IJNet');
        $query->where[1]['conditions'][$index]['value'] = explode(',', $accounts);
        $query->where[1]['conditions'][$index]['operator'] = 'IN';
      }   
    }  
  }
}

function _fe_knight_foundation_get_last_posts_authors() {
  global $language;
  $knight_foundation_topic = array(
    'en' => '913',
    'es' => '914',
    'ru' => '915',
    'ar' => '916',
    'zh-hans' => '917',
    'fa' => '919',
    'pt-br' => '918',
  );

  $last_posts_authors =
    _fe_news_get_last_posts_authors(
      $knight_foundation_topic[$language->language]
    );

  return $last_posts_authors;
}

/**
 * Implements hook_menu().
 */
function fe_knight_foundation_menu() {
  $items = array();
  $items['admin/config/administration/knight-tweets'] = array(
    'title'           => t('Admin for Knight Foundation Twitter accounts'),
    'description'  => t('Knight Foundation\'s twitter accounts admin page'),
    'page callback'   => 'drupal_get_form',
    'page arguments' => array('fe_knight_foundation_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );  
  return $items;
}


function fe_knight_foundation_form() {
  $form['twitters'] = array(
    '#title' => t('Twitter list'),
    '#type' => 'textarea',
    '#description' => t('Write down all the twitter acounts that you want to get listed on knight foundation\'s twitter block, separated by a comma'),
    '#default_value' => variable_get('fe_knight_foundation_tweets', 'IJNet'),
  );
  $form['submit'] = array(                                                                                                                                                      
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function fe_knight_foundation_form_submit($form, &$form_state) {
  $accounts = $form_state['input']['twitters'];
  variable_set('fe_knight_foundation_tweets', $accounts);
  drupal_set_message(t('Your configuration has been succesfully saved.'), 'status');
  return;
}
