<?php
/**
 * @file
 * Code for the Videos feature.
 */

include_once 'fe_videos.features.inc';

/**
 * Implements hook_theme()
 */

function fe_videos_theme() {
  return array(
    'node__video' => array(
      'variables' => array('node' => array()),
      'template' => 'theme/node--video',
    ),
    'video_category_search' => array(
      'variables' => array('categories' => array()),
      'template' => 'theme/video_search',
    ),
  );
}

/**
 * Implements hook_block_info()
 */

function fe_videos_block_info() {
  $blocks = array(
    'fe_videos_search' => array(
      'info' => 'Videos Search Bar',
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */

function fe_videos_block_view($delta) {
  $block = array();
  if ($delta == 'fe_videos_search') {
    $vocabulary = taxonomy_vocabulary_machine_name_load('topic');
    $terms = taxonomy_get_tree($vocabulary->vid, 0, null, true);
    global $language;

    $query = db_select('taxonomy_term_data', 'd');
    $query->join('taxonomy_index', 'i', 'd.tid = i.tid');
    $query->join('node', 'n', 'i.nid = n.nid');
    $query
      ->condition('d.vid', 3)
      ->condition('n.type', 'video')
      ->condition('n.language', $language->language)
      ->fields('d', array('tid', 'name'))
      ->groupBy('d.tid');

    $result = $query->execute()->fetchAll();

    $options = array();
    foreach ($result as $term) {
      $options[$term->tid] = $term->name;
      asort($options);
    }
    $vars = array(
      'categories' => $options,
    );
    drupal_add_js(drupal_get_path('module', 'fe_videos') .'/js/fe_videos.js');
    $block['subject'] = '';
    $block['content'] = theme('video_category_search', $vars);
  }
  return $block;
}

/**
 * Implements hook_form_alter()
 */
 
function fe_videos_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'comment_node_video_form') {
    hide($form['author']);
  }
}

/**
 * Implements hook_preprocess_node()
 */

function fe_videos_preprocess_node(&$vars) {
  if ($vars['node']->type == 'video') {
    $vars['date'] = format_date($vars['node']->created, 'video_short_format');
    if (strlen($vars['title']) > 100) {
      $vars['title'] = substr($vars['title'], 0, 100) . '...';
    }

    ///////////////
    $topics = module_invoke('fe_news', 'block_view', 'field_topic_block');
    $vars['topics'] = $topics['content'];
  }
}

/**
 * Implements hook_views_pre_view()
 */
function fe_videos_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'video_category_search') {
    if (!empty($args)) {
      $term = taxonomy_term_load($args[0]);
      $options = array(
        'id' => 'area',
        'table' => 'views',
        'field' => 'area',
        'empty' => FALSE,
        'content' => t('<h1 id="page-title"> Videos in @topic</h1>', array('@topic' => $term->name)),
        'format' => 'full_html',
        'tokenize' => 0,
      );
      $view->display_handler->set_option('header', array('text' => $options));
    }
  }
}

