<?php
/**
 * @file
 * Code for the Carebot tracker.
 */

/**
 * Implements hook_page_alter().
 */
function ijnet_carebot_page_alter(&$page) {
  // Only for frontend page
  if (! preg_match("/admin\/.*/", current_path())) {
  	$js_file = drupal_get_path('module', 'ijnet_carebot') . '/js/carebot-tracker.min.js';
  	drupal_add_js($js_file);
    
    $script_code = "(function(percent, seconds) {
      var tracker = new CarebotTracker.ScrollTracker('page-wrapper', function(percent, seconds) {
        var eventData = {
          'hitType': 'event',
          'eventCategory': 'page',
          'eventAction': 'scroll-depth',
          'eventLabel': percent,
          'eventValue': seconds
        };
        ga('send', eventData); // Assumes GA has already been set up.
      });
    })(jQuery);";

    drupal_add_js($script_code, array(
        'scope' => 'footer',
        'type' => 'inline',
        'every_page' => TRUE,
        'weight' => 2,
    ));
  }
}
