<?php
/**
 * @file
 * Code for the Carebot tracker.
 */

/**
 * Implements hook_page_alter().
 */
function ijnet_carebot_page_alter(&$page) {
  // Only for frontend page
  if (! preg_match("/admin\/.*/", current_path())) {
  	$js_file = drupal_get_path('module', 'ijnet_carebot') . '/js/carebot-tracker.min.js';
  	drupal_add_js($js_file);

    $ijnet_carebot_js = drupal_get_path('module', 'ijnet_carebot') . '/js/ijnet-carebot.js';
    drupal_add_js($ijnet_carebot_js);
  }
}
