<?php

/**
 * Implements hook_block_info().
 */
function jsonblocks_block_info() {
  $blocks = _jsonblocks_get_block_info(_jsonblocks_get_json_blocks());
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function jsonblocks_block_view($delta = NULL) {

  $function_name = 'json_blocks_view_' . str_replace('-', '_', $delta);
  $block_data = _jsonblocks_get_json_blocks();
  if (function_exists($function_name)) {
    $block = $function_name();
  }
  else {
    // dynamic blocks
    $block = array('content' => theme($delta, NULL));
  }
  if (isset($block_data[$delta])) {
    if(isset($block_data[$delta]['css'])) {
      drupal_add_css(drupal_get_path('module', 'jsonblocks') . '/css/' . $block_data[$delta]['css']);
    }
    if (isset($block_data[$delta]['js'])) {
      drupal_add_js(drupal_get_path('module', 'jsonblocks') . '/js/' . $block_data[$delta]['js']);
    }
  }

  return $block;
}

/**
 * hook_form_alter()
 * Cleanup comments form.
 */

function jsonblocks_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_site_form') {
    $form['subject']['#title'] = t('COUNTRY');
    $form['name']['#title'] = t('NAME');
    $form['mail']['#title'] = t('EMAIL ADDRESS');
    $form['message']['#title'] = t('QUESTION OR COMMENT');
    $form['copy']['#type'] = 'hidden';
    $form['actions']['submit']['#value'] = t('Submit');
  }
}

/**
 * hook_theme()
 */
function jsonblocks_theme() {
  $blocks = _jsonblocks_get_json_blocks();
  $theme_vars = array();

  foreach ($blocks as $block_name => $block) {
    $tpl_name = drupal_html_class($block_name);

    $theme_vars[$block_name] = array(
        'variables' => array(),
        'template' => 'theme/' . $tpl_name,
    );
  }
  return $theme_vars;
}

/*
 * internal function "get json blocks"
 */
function _jsonblocks_get_json_blocks() {
  $file_path = drupal_realpath( drupal_get_path('module', 'jsonblocks') ) . '/jsonblocks.json';
  $json_file = file_get_contents($file_path);
  $json_arr = json_decode($json_file, TRUE); // decode as assoc array
  return $json_arr;
}

function _jsonblocks_get_block_info($blocks_data) {
  $blocks = array();
  foreach ($blocks_data as $delta => $block_data) {
    $blocks[$delta] = array(
      'info' => $block_data['info'],
    );
  }
  return $blocks;
}

function json_blocks_view_login_block() {
  $block_data = _jsonblocks_get_json_blocks();
  global $user;
  if ($user->uid) {
    $logged = true;
  }
  else {
    $logged = false;
  }
  $vars['logged'] = $logged;
  $block = array('content' => theme('login_block', $vars));
  return $block;
}

function json_blocks_view_social_block() {
  global $language;
  $social_media_items = _fe_social_get_social_media_items($language->language);
  $block = array('content' => theme('social-block', array('urls' => $social_media_items)));
  return $block;
}

/**
 * Implements hook_mail_alter().
 */
function jsonblocks_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {
    $email = array(
      'en' => 'ijneteditor@icfj.org',
      'es' => 'santiagosanchez86@gmail.com',
      'ru' => 'IJNetRussian@icfj.org',
      'ar' => 'madonna.khafaja@gmail.com',
      'zh-hans' => 'jhuang@icfj.org',
      'fa' => 'persianeditor@icfj.org',
      'pt-br' => 'globaljournalist2004@yahoo.com',
    );
    global $language;
    $message['to'] = isset($email[$language->language]) ?
      $email[$language->language] : $email['en'];
  }
}

function json_blocks_view_facebook_like() {
  global $language;
  $all_items = _fe_social_get_social_media_items($language->language);
  $url = $all_items['facebook']['url'];
  return array('content' => theme('facebook-like', array('url' => $url)));
}

