<?php

/**
 * Implements hook_block_info().
 */
function jsonblocks_block_info() {
  $blocks = _jsonblocks_get_block_info(_jsonblocks_get_json_blocks());
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function jsonblocks_block_view($delta = NULL) {

  $function_name = 'json_blocks_view_' . str_replace('-', '_', $delta);
  $block_data = _jsonblocks_get_json_blocks();
  if (function_exists($function_name)) {
    $block = $function_name();
  }
  else {
    // dynamic blocks
    $block = array('content' => theme($delta, NULL));
  }
  if (isset($block_data[$delta])) {
    if(isset($block_data[$delta]['css'])) {
      drupal_add_css(drupal_get_path('module', 'jsonblocks') . '/css/' . $block_data[$delta]['css']);
    }
    if (isset($block_data[$delta]['js'])) {
      drupal_add_js(drupal_get_path('module', 'jsonblocks') . '/js/' . $block_data[$delta]['js']);
    }
  }

  return $block;
}

/**
 * hook_form_alter()
 * Cleanup comments form.
 */

function jsonblocks_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_site_form') {
    $form['subject']['#title'] = t('COUNTRY');
    $form['name']['#title'] = t('NAME');
    $form['mail']['#title'] = t('EMAIL ADDRESS');
    $form['message']['#title'] = t('QUESTION OR COMMENT');
    $form['copy']['#type'] = 'hidden';
    $form['actions']['submit']['#value'] = t('Submit');
  }
}

/**
 * hook_theme()
 */
function jsonblocks_theme() {
  $blocks = _jsonblocks_get_json_blocks();
  $theme_vars = array();

  foreach ($blocks as $block_name => $block) {
    $tpl_name = drupal_html_class($block_name);

    $theme_vars[$block_name] = array(
        'variables' => array(),
        'template' => 'theme/' . $tpl_name,
    );
  }
  return $theme_vars;
}

/*
 * internal function "get json blocks"
 */
function _jsonblocks_get_json_blocks() {
  $file_path = drupal_realpath( drupal_get_path('module', 'jsonblocks') ) . '/jsonblocks.json';
  $json_file = file_get_contents($file_path);
  $json_arr = json_decode($json_file, TRUE); // decode as assoc array
  return $json_arr;
}

function _jsonblocks_get_block_info($blocks_data) {
  $blocks = array();
  foreach ($blocks_data as $delta => $block_data) {
    $blocks[$delta] = array(
      'info' => $block_data['info'],
    );
  }
  return $blocks;
}

function json_blocks_view_login_block() {
  $block_data = _jsonblocks_get_json_blocks();
  global $user;
  if ($user->uid) {
    $logged = true;
  }
  else {
    $logged = false;
  }
  $vars['logged'] = $logged;
  $block = array('content' => theme('login_block', $vars));
  return $block;
}

function json_blocks_view_social_block() {
  $all_items = array(
    'en' => array(
        array(
            'url' => 'https://www.facebook.com/IJNet',
            'class' => 'social-icon-facebook',
        ),
        array(
            'url' => 'http://twitter.com/ijnet',
            'class' => 'social-icon-twitter',
        ),
        array(
            'url' => 'http://www.youtube.com/ijnetvideo',
            'class' => 'social-icon-youtube',
        ),
        array(
            'url' => 'http://www.linkedin.com/groups/International-Journalists-Network-IJNet-3734352',
            'class' => 'social-icon-in',
        ),
        array(
            'url' => 'https://plus.google.com/109438369213951959896/posts',
            'class' => 'social-icon-gplus',
        ),
        array(
            'url' => '/rss.xml',
            'class' => 'social-icon-rss',
        )
    ),
    'es' => array(
        array(
            'url' => 'https://www.facebook.com/pages/IJNet-Espa%C3%B1ol/120641331286811',
            'class' => 'social-icon-facebook',
        ),
        array(
            'url' => 'https://twitter.com/ijnetEs',
            'class' => 'social-icon-twitter',
        ),
        array(
            'url' => 'https://www.youtube.com/user/IJNetEspanol',
            'class' => 'social-icon-youtube',
        ),
        array(
            'url' => 'https://plus.google.com/100360709746549610122/posts',
            'class' => 'social-icon-gplus',
        ),
        array(
            'url' => '/rss.xml',
            'class' => 'social-icon-rss',
        )
    ),
    'ru' => array(
        array(
            'url' => 'https://www.facebook.com/RussianIJNet?ref=ts',
            'class' => 'social-icon-facebook',
        ),
        array(
            'url' => 'https://twitter.com/IJNet_Russian',
            'class' => 'social-icon-twitter',
        ),
        array(
            'url' => 'https://www.youtube.com/user/IJNetVideo',
            'class' => 'social-icon-youtube',
        ),
      array(
            'url' => '/rss.xml',
            'class' => 'social-icon-rss',
        )
    ),
    'ar' => array(
        array(
            'url' => 'https://www.facebook.com/IJNetArabic',
            'class' => 'social-icon-facebook',
        ),
        array(
            'url' => 'https://twitter.com/ijnetarabic',
            'class' => 'social-icon-twitter',
        ),
        array(
            'url' => 'https://www.youtube.com/user/ijnetarabic',
            'class' => 'social-icon-youtube',
        ),
        array(
            'url' => '',
            'class' => 'social-icon-in',
        ),
        array(
            'url' => '',
            'class' => 'social-icon-gplus',
        ),
        array(
            'url' => '/rss.xml',
            'class' => 'social-icon-rss',
        )
    ),
    'zh-hans' => array(
        array(
            'url' => 'https://www.facebook.com/IJNet',
            'class' => 'social-icon-facebook',
        ),
        array(
            'url' => 'https://twitter.com/IJNET',
            'class' => 'social-icon-twitter',
      ),
      array(
          'url' => 'http://weibo.com/ijnet',
          'class' => 'social-icon-weibo',
      ),
    array(
          'url' => '/rss.xml',
          'class' => 'social-icon-rss',
      )
  ),
  'fa' => array(
      array(
          'url' => 'https://www.facebook.com/IJNetPersian',
          'class' => 'social-icon-facebook',
      ),
      array(
          'url' => 'https://twitter.com/IJNetPersian',
          'class' => 'social-icon-twitter',
      ),
      array(
          'url' => 'https://www.youtube.com/user/IJNetVideo',
          'class' => 'social-icon-youtube',
      ),
      array(
          'url' => '/rss.xml',
          'class' => 'social-icon-rss',
      )
    ),
    'pt-br' => array(
      array(
          'url' => 'https://www.facebook.com/pages/Rede-de-Jornalistas-Internacionais-IJNet/117673284936246?ref=ts',
          'class' => 'social-icon-facebook',
      ),
      array(
          'url' => 'https://twitter.com/IJNetPortugues',
          'class' => 'social-icon-twitter',
      ),
      array(
          'url' => 'https://www.youtube.com/user/IJNetVideo',
          'class' => 'social-icon-youtube',
      ),
      array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
      )
    )
  );
  global $language;
  $block = array('content' => theme('social-block', array('urls' => $all_items[$language->language])));
  return $block;
}

/**
 * Implements hook_mail_alter().
 */

function jsonblocks_mail_alter(&$message) {
  if ($message['id'] == 'contact_page_mail') {
    $email = array(
      'en' => 'ijneteditor@icfj.org',
      'es' => 'santiagosanchez86@gmail.com',
      'ru' => 'IJNetRussian@icfj.org',
      'ar' => 'madonna.khafaja@gmail.com',
      'zh-hans' => 'jhuang@icfj.org',
      'fa' => 'persianeditor@icfj.org',
      'pt-br' => 'globaljournalist2004@yahoo.com',
    );
    global $language;
    $message['to'] = $email[$language->language];
  }
}
