<?php
/**
 * @file
 * Code for the Social feature.
 */

include_once 'fe_social.features.inc';

function fe_social_preprocess_page(&$vars) {
  if (isset($vars['node'])) {
    if ($vars['node']->type == 'news') {
      $header_js = '
        <script type="text/javascript">var switchTo5x=true;</script>
        <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
        <script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
        ';
      drupal_add_js($header_js, array('type' => 'inline', 'scope' => 'header'));

      $footer_js = '
        <script type="text/javascript">stLight.options({publisher: "ur-d73e831-ed94-5abd-edb-77472e6cac2e", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
        <script>
          var options={ "publisher": "ur-d73e831-ed94-5abd-edb-77472e6cac2e", "position": "left", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "email"]}};
          var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
        </script>
        ';
      drupal_add_js($footer_js, array('type' => 'inline', 'scope' => 'footer'));
    }
  }
}
