<?php

/**
 * @file
 * Code for the Social feature.
 */

include_once 'fe_social.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function fe_social_preprocess_node(&$vars) {

  // Solo agrego los meta en la pagina de detalle
  if ($vars['page'] != TRUE) {
    return;
  }

  $node = $vars['node'];

  if ($node->type == 'news') {
    fe_social_get_news_og_meta($node);
  }
  elseif ($node->type == 'training_opportunity') {
    fe_social_get_training_opportunity_og_meta($node);
  }
}

/**
 * Implements hook_node_view().
 */
function fe_social_node_view($node, $view_mode, $langcode) {
  $a = array('news', 'video', 'training_opportunity');
  if ((in_array($node->type, $a)) && ($view_mode == 'full')) {
    $script = array(
      '#type' => 'markup',
      '#markup' => '<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-543e9b6e138d6797" async></script>',
    );
    drupal_add_html_head($script, 'fe_social_addthis_script');
  }
}

/**
 * Implements hook_views_query_alter()
 */
function fe_social_views_query_alter(&$view, &$query) {
  $twitter_accounts = _fe_social_get_twitter_accounts();

  if ($view->name == 'twitter' && $view->current_display == 'tweets_home_block') {
    global $language;
    $lang = $language->language;
    if (($lang != 'en') && (array_key_exists($lang, $twitter_accounts))) {
      foreach ($query->where[1]['conditions'] as $index => $condition) {
        if ($query->where[1]['conditions'][$index]['field'] == 'twitter.screen_name') {
          $query->where[1]['conditions'][$index]['value'] = $twitter_accounts[$lang];
        }
      }
    }
  }
}

/**
 * Implements hook_form_alter()
 */
function fe_social_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['search_block_form']['#attributes']['placeholder'] = t('Search the site...');
  }
  elseif ($form_id == 'lang_dropdown_form') {
    $path = explode('/', current_path());
    $tid = isset($path[1]) ? $path[1] : NULL;
    if (($path[0] == 'news') && (is_numeric($tid))) {
      $content_type = 'news';
      _fe_social_update_language_form_redirects($form, $content_type, $tid);
    }
    elseif (($path[0] == 'opportunities') && (is_numeric($tid))) {
      $content_type = 'opportunities';
      _fe_social_update_language_form_redirects($form, $content_type, $tid);
    }
    elseif (($path[0] == 'videos') && (is_numeric($path[2]))) {
      $tid = $path[2];
      $content_type = 'videos';
      _fe_social_update_language_form_redirects($form, $content_type, $tid);
    }
  }
}

function _fe_social_get_twitter_handle() {
  global $language;
  $twitter_accounts = _fe_social_get_twitter_accounts();
  $twitter_handle = array_key_exists($language->language, $twitter_accounts) ? $twitter_accounts[$language->language] : $twitter_accounts['en'];

  return $twitter_handle;
}

function _fe_social_get_twitter_accounts() {
  $twitter_accounts = array(
    'en' => 'IJNet',
    'ar' => 'IJNetArabic',
    'es' => 'ijnetEs',
    'fa' => 'IJNetPersian',
    'pt-br' => 'IJNetPortugues',
    'ru' => 'IJNet_Russian',
  );

  return $twitter_accounts;
}

function fe_social_get_news_og_meta($node) {
  $lang = $node->language;
  $title = isset($node->title_field[$lang]) ? $node->title_field[$lang][0]['safe_value'] : $node->title_field[LANGUAGE_NONE][0]['safe_value'];
  $url = url('node/' . $node->nid, array('absolute' => TRUE));
  $description = isset($node->body[$lang]) ? strip_tags($node->body[$lang][0]['safe_summary']) : strip_tags($node->body[LANGUAGE_NONE][0]['safe_summary']);
  $image_keys = array_keys($node->field_image);
  $image = isset($node->field_image[$lang]) ? file_create_url($node->field_image[$lang][0]['uri']) : file_create_url($node->field_image[$image_keys[0]][0]['uri']);

  fe_social_add_og_meta_tags($title, $url, $description, $image);
}

function fe_social_get_training_opportunity_og_meta($node) {
  $lang = $node->language;
  $title = $node->title;
  $url = url('node/' . $node->nid, array('absolute' => TRUE));
  $description = isset($node->body[$lang]) ? strip_tags($node->body[$lang][0]['safe_summary']) : strip_tags($node->body[LANGUAGE_NONE][0]['safe_summary']);
  $logo = _fe_social_get_ijnet_logo_by_lang($lang);
  $image = drupal_realpath($logo['path']);

  fe_social_add_og_meta_tags($title, $url, $description, $image);
}

function _fe_social_get_ijnet_logo_by_lang($language = 'en') {
  $ijnet_logo_name = ($language == 'en') ? 'logo.png' : 'logo_' . str_replace('-', '_', $language) . '.png';
  $ijnet_logo_path = drupal_get_path('theme', 'ijnet') . '/' . $ijnet_logo_name;
  $logo = array(
    'path' => $ijnet_logo_path,
    'alt' => 'ijnet_logo',
  );

  return $logo;
}

function _fe_social_get_social_media_items($language = 'en') {
  $images_path = drupal_get_path('module', 'fe_newsletter') . '/theme/images/';
  $items = array(
    'en' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNet',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'http://twitter.com/ijnet',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'http://www.youtube.com/ijnetvideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'linkedin' => array(
        'url' => 'https://www.linkedin.com/company/5326144?trk=tyah&trkInfo=tarId%3A1409937031161%2Ctas%3Ainternational%20journalists%27%20%2Cidx%3A3-1-4',
        'class' => 'social-icon-in',
        'image' => array(
          'path' => $images_path . 'social_04.png',
          'alt' => 'linkedin',
        ),
      ),
      'google+' => array(
        'url' => 'https://plus.google.com/109438369213951959896/posts',
        'class' => 'social-icon-gplus',
        'image' => array(
          'path' => $images_path . 'social_05.png',
          'alt' => 'google+',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'es' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/pages/IJNet-Espa%C3%B1ol/120641331286811',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/ijnetEs',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetEspanol',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'google+' => array(
        'url' => 'https://plus.google.com/100360709746549610122/posts',
        'class' => 'social-icon-gplus',
        'image' => array(
          'path' => $images_path . 'social_05.png',
          'alt' => 'google+',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'ru' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/RussianIJNet?ref=ts',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNet_Russian',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'ar' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNetArabic',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/ijnetarabic',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/ijnetarabic',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'zh-hans' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNet',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNET',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'weibo' => array(
        'url' => 'http://weibo.com/ijnet',
        'class' => 'social-icon-weibo',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'webio',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'fa' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNetPersian',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNetPersian',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'pt-br' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/pages/Rede-de-Jornalistas-Internacionais-IJNet/117673284936246?ref=ts',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNetPortugues',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss/blog',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
  );

  return $items[$language];
}

function fe_social_add_og_meta_tags($title, $url, $description, $image) {
  $og_meta = array(
    'fe_social_og_title' => array(
      'property' => 'og:title',
      'content' => $title,
    ),
    'fe_social_og_url' => array(
      'property' => 'og:url',
      'content' => $url,
    ),
    'fe_social_og_desc' => array(
      'property' => 'og:description',
      'content' => $description,
    ),
    'fe_social_og_img' => array(
      'property' => 'og:image',
      'content' => $image,
    ),
  );
  foreach ($og_meta as $key => $hdr) {
    $og_tag = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => $hdr['property'],
        'content' => trim($hdr['content']),
      ),
    );
    drupal_add_html_head($og_tag, $key);
  }

  $tw_meta = array(
    'fe_social_tw_card' => array(
      'name' => 'twitter:card',
      'content' => 'summary',
    ),
    'fe_social_tw_site' => array(
      'name' => 'twitter:site',
      'content' => t('@IJNet'),
    ),
    'fe_social_tw_title' => array(
      'name' => 'twitter:title',
      'content' => $title,
    ),
    'fe_social_tw_url' => array(
      'name' => 'twitter:url',
      'content' => $url,
    ),
    'fe_social_tw_desc' => array(
      'name' => 'twitter:description',
      'content' => $description,
    ),
    'fe_social_tw_img' => array(
      'name' => 'twitter:image',
      'content' => $image,
    ),
  );
  foreach ($tw_meta as $key => $hdr) {
    $tw_tag = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => $hdr['name'],
        'content' => trim($hdr['content']),
      ),
    );
    drupal_add_html_head($tw_tag, $key);
  }
}
/**
 */
function _fe_social_update_language_form_redirects(&$form, $content_type, $tid) {
  $tids_by_language = _fe_social_get_tids_by_language($tid);
  $languages = language_list();
  $content_type = $content_type == 'videos' ? $content_type . 'topic' : $content_type;
  foreach ($languages as $lang_code => $language) {
    $form[$lang_code]['#default_value'] = '/' . $lang_code . '/' . $content_type . '/' . $tids_by_language[$lang_code];
  }
}

/**
 */
function _fe_social_get_tids_by_language($tid) {
  $tids_by_language = array();
  $languages = language_list();
  $term = taxonomy_term_load($tid);
  foreach ($languages as $lang_code => $language) {
    $term_by_language = i18n_taxonomy_term_get_translation($term, $lang_code);
    $tids_by_language[$lang_code] = $term_by_language ? $term_by_language->tid : $term->tid;
  }

  return $tids_by_language;
}


