<?php
/**
 * @file
 * Code for the Social feature.
 */

include_once 'fe_social.features.inc';

function fe_social_preprocess_page(&$vars) {
  if (isset($vars['node'])) {
    if ($vars['node']->type == 'news') {
      $twitter_handle = _fe_social_get_twitter_handle();
      //drupal_add_js('var switchTo5x=true', array('type' => 'inline', 'scope' => 'header'));
      //drupal_add_js('http://w.sharethis.com/button/buttons.js', 'external');
      //drupal_add_js('http://w.sharethis.com/loader.js', 'external');
      $header_js = '
        <script type="text/javascript">var switchTo5x=true;</script>
        <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
        <script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
        ';
      drupal_add_js($header_js, array('type' => 'inline', 'scope' => 'header'));
      $footer_js = '
        <script type="text/javascript">
            stLight.options({
                publisher: "ur-d73e831-ed94-5abd-edb-77472e6cac2e", 
                doNotHash: false, 
                doNotCopy: false, 
                hashAddressBar: false
            });
        </script>
        <script>
          var options={ "publisher": "ur-d73e831-ed94-5abd-edb-77472e6cac2e", 
                "position": "left",
                "ad": { "visible": false,
                        "openDelay": 5,
                        "closeDelay": 0},
                "chicklets": { "items": ["facebook", "twitter", "email", "sharethis"]},
                "chicklets_params": { "twitter" : { "st_via" : "' . $twitter_handle . '" } }
                };
          var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
        </script>
        ';
      drupal_add_js($footer_js, array('type' => 'inline', 'scope' => 'footer'));
    }
  }
}

function _fe_social_get_twitter_handle() {
  global $language;
  $twitter_accounts = _fe_social_get_twitter_accounts();
  $twitter_handle = array_key_exists($language->language, $twitter_accounts) ?
    $twitter_accounts[$language->language] :
    $twitter_accounts['en'];

  return $twitter_handle;
}

function _fe_social_get_twitter_accounts() {
  $twitter_accounts = array(
    'en' => 'IJNet',
    'ar' => 'IJNetArabic',
    'es' => 'ijnetEs',
    'fa' => 'IJNetPersian',
    'pt-br' => 'IJNetPortugues',
    'ru' => 'IJNet_Russian',
  );

  return $twitter_accounts;
}

/**
 * Implements hook_preprocess_node().
 */
function fe_social_preprocess_node(&$vars) {

  // Solo agrego los meta en la pagina de detalle
  if ($vars['page'] != TRUE)  {
    return;
  }

  $node = $vars['node'];

  if ($node->type == 'news') {
    fe_social_get_news_og_meta($node);
  }
  elseif ($node->type == 'training_opportunity') {
    fe_social_get_training_opportunity_og_meta($node);
  }
}

function fe_social_get_news_og_meta($node) {
  $lang = $node->language;
  $title = isset($node->title_field[$lang]) ?
    $node->title_field[$lang][0]['safe_value'] :
    $node->title_field[LANGUAGE_NONE][0]['safe_value'];
  $url = url('node/' . $node->nid, array('absolute' => TRUE));
  $description = isset($node->body[$lang]) ?
    strip_tags($node->body[$lang][0]['safe_summary']) :
    strip_tags($node->body[LANGUAGE_NONE][0]['safe_summary']);
  $image = isset($node->field_image[$lang]) ?
    file_create_url($node->field_image[$lang][0]['uri']) :
    file_create_url($node->field_image[LANGUAGE_NONE][0]['uri']);

  fe_social_add_og_meta_tags($title, $url, $description, $image);
}

function fe_social_get_training_opportunity_og_meta($node) {
  $lang = $node->language;
  $title = $node->title;
  $url = url('node/' . $node->nid, array('absolute' => TRUE));
  $description = isset($node->body[$lang]) ?
    strip_tags($node->body[$lang][0]['safe_summary']) :
    strip_tags($node->body[LANGUAGE_NONE][0]['safe_summary']);
  $logo = _fe_social_get_ijnet_logo_by_lang($lang);
  $image = drupal_realpath($logo['path']);

  fe_social_add_og_meta_tags($title, $url, $description, $image);
}

function _fe_social_get_ijnet_logo_by_lang($language = 'en') {
  $ijnet_logo_name = ($language == 'en') ?
    'logo.png' :
    'logo_' . str_replace('-', '_', $language) . '.png';
  $ijnet_logo_path = drupal_get_path('theme', 'ijnet') . '/' . $ijnet_logo_name;
  $logo = array(
    'path' => $ijnet_logo_path,
    'alt' => 'ijnet_logo',
  );

  return $logo;
}

function _fe_social_get_social_media_items($language = 'en') {
  $images_path = drupal_get_path('module', 'fe_newsletter') . '/theme/images/';
  $items = array(
    'en' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNet',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'http://twitter.com/ijnet',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path'=> $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'http://www.youtube.com/ijnetvideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'linkedin' => array(
        'url' => 'http://www.linkedin.com/groups/International-Journalists-Network-IJNet-3734352',
        'class' => 'social-icon-in',
        'image' => array(
          'path' => $images_path . 'social_04.png',
          'alt' => 'linkedin',
        ),
      ),
      'google+' => array(
        'url' => 'https://plus.google.com/109438369213951959896/posts',
        'class' => 'social-icon-gplus',
        'image' => array(
          'path' => $images_path . 'social_05.png',
          'alt' => 'google+',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      )
    ),
    'es' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/pages/IJNet-Espa%C3%B1ol/120641331286811',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/ijnetEs',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetEspanol',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'google+' => array(
        'url' => 'https://plus.google.com/100360709746549610122/posts',
        'class' => 'social-icon-gplus',
        'image' => array(
          'path' => $images_path . 'social_04.png',
          'alt' => 'google+',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      )
    ),
    'ru' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/RussianIJNet?ref=ts',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNet_Russian',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      )
    ),
    'ar' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNetArabic',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/ijnetarabic',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/ijnetarabic',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'zh-hans' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNet',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNET',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'weibo' => array(
        'url' => 'http://weibo.com/ijnet',
        'class' => 'social-icon-weibo',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'webio',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'fa' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/IJNetPersian',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNetPersian',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
    'pt-br' => array(
      'facebook' => array(
        'url' => 'https://www.facebook.com/pages/Rede-de-Jornalistas-Internacionais-IJNet/117673284936246?ref=ts',
        'class' => 'social-icon-facebook',
        'image' => array(
          'path' => $images_path . 'social_01.png',
          'alt' => 'facebook',
        ),
      ),
      'twitter' => array(
        'url' => 'https://twitter.com/IJNetPortugues',
        'class' => 'social-icon-twitter',
        'image' => array(
          'path' => $images_path . 'social_02.png',
          'alt' => 'twitter',
        ),
      ),
      'youtube' => array(
        'url' => 'https://www.youtube.com/user/IJNetVideo',
        'class' => 'social-icon-youtube',
        'image' => array(
          'path' => $images_path . 'social_03.png',
          'alt' => 'youtube',
        ),
      ),
      'rss' => array(
        'url' => '/rss.xml',
        'class' => 'social-icon-rss',
        'image' => array(
          'path' => $images_path . 'social_06.png',
          'alt' => 'rss',
        ),
      ),
    ),
  );

  return $items[$language];
}
function fe_social_add_og_meta_tags($title, $url, $description, $image) {
  $og_meta = array(
    'fe_social_og_title' => array(
      'property' => 'og:title',
      'content' => $title,
    ),
    'fe_social_og_url' => array(
      'property' => 'og:url',
      'content' => $url,
    ),
    'fe_social_og_desc' => array(
      'property' => 'og:description',
      'content' => $description,
    ),
    'fe_social_og_img' => array(
      'property' => 'og:image',
      'content' => $image,
    ),
   );
  foreach($og_meta as $key => $hdr) {
    $og_tag = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => $hdr['property'],
        'content' => $hdr['content']
      ),
    );
    drupal_add_html_head($og_tag, $key);
  }
}

/**
 * Implements hook_views_query_alter()
 */
function fe_social_views_query_alter(&$view, &$query) {
  $twitter_accounts = _fe_social_get_twitter_accounts();

  if ($view->name == 'twitter' && $view->current_display == 'tweets_home_block') {
    global $language;
    $lang = $language->language;
    if (($lang != 'en') && (array_key_exists($lang, $twitter_accounts))) {
      foreach($query->where[1]['conditions'] as $index => $condition) {
        if ($query->where[1]['conditions'][$index]['field'] == 'twitter.screen_name') {
          $query->where[1]['conditions'][$index]['value'] = $twitter_accounts[$lang];
        }
      }
    }
  }
}
